### ISSUE TITLE
http://127.0.0.1:8000/admin/ url don't show anything from models.py.

### ISSUE THREAD

**Issue by Samsul-Alam-STP** [offwhitepanda/DjangoIrisDataDashboard#1]
### Problem

The `models.py` file in the project is not registered in the `admins.py` file. As a result, when accessing the `/admin` URL, nothing is displayed in the admin interface.

### Expected Behavior

The models defined in `models.py` should be properly registered in `admins.py` so that they can be managed through the admin interface.

### Steps to Reproduce

1. Navigate to the project directory.
2. Open `admins.py` and verify that the models are being registered correctly.
3. Confirm that the `models.py` file contains the relevant model definitions.

### Possible solutions
- Register the model classes in the admins.py file.

**Comment by richard-hurley** [comment]
Hi, thank you for your contribution. The file has been updated and now correctly reflects within the admin view.
